### ISSUE TITLE
tmate-server chart

### ISSUE THREAD

**Issue by BobyMCbobs** [sharingio/helm-charts#1]

**Comment by BobyMCbobs** [comment]
Using the `docker.io/sharingio/tmate-master:latest` image in the init container of the master deployment.
`mix` is installed in the container but currently this error is coming up when migrations are run
```
$ kubectl -n sharingio-tmate logs -c tmate-migrate deployment/tmate-master
** (Mix) The task "ecto.create" could not be found
```

**Comment by BobyMCbobs** [comment]
Building the latest dev image, it has the error

```
01:47:29.244 [error] GenServer #PID<0.269.0> terminating
** (DBConnection.ConnectionError) tcp connect (postgres:5432): non-existing domain - :nxdomain
    (db_connection) lib/db_connection/connection.ex:87: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for Tmate.Repo couldn't be created: killed
```
